### ISSUE TITLE
Functionality of the gem

### ISSUE THREAD

**Issue by andrew2net** [metanorma/isoics#1]
@ronaldtse Suppose the gem should search and return ICS data by field, group and subgroup codes. Am I right?

**Comment by ronaldtse** [comment]
Yes indeed! e.g., `IsoIcs.get("33.010.33") => #Object` ?

**Comment by andrew2net** [comment]
Did it. Should the gem be published?

**Comment by ronaldtse** [comment]
Definitely. Can you help prepare the gem spec, similar to our other gems, e.g., `ribose-ruby`?

**Comment by andrew2net** [comment]
Published
